### ISSUE TITLE
Is the challenge deadline 30th Sep or 25th Sep?

### ISSUE THREAD

**Issue by samsdolphin** [water-horse/ICCV2023_SLAM_Challenge#10]
Hi, when we submit the result to the gradescope, the website says the due date is 30th Sep. So is the deadline extended or it remains on 25th Sep?

**Comment by yuanjun-gao** [comment]
The deadline is 25th Sep for now.
Will come back to this issue to post the new deadline if it is extended.

**Comment by yuanjun-gao** [comment]
Hi, the deadline is extended.
