### ISSUE TITLE
can i resubmit the results many times in one day?

### ISSUE THREAD

**Issue by HLkyss** [water-horse/ICCV2023_SLAM_Challenge#11]
i notice that the Challenge Rules says "Every day a team can submit for at most once on gradescope and the submission must be in a certain time window". But the Resubmit button in the gradescope page seems always available. So can i resubmit the results many times in one day?

**Comment by yuanjun-gao** [comment]
To facilitate better algorithm debugging for everyone recently, we will allow multiple daily submissions until 20 Sept. Starting from 21 Sept, only one submission per day is allowed.

This notice has also been updated on the website ([link](https://superodometry.com/iccv23_challenge_VI), [link](https://superodometry.com/iccv23_challenge_LiI), [link](https://superodometry.com/iccv23_challenge_Mul)).
