### ISSUE TITLE
calibration datasets

### ISSUE THREAD

**Issue by zzzzxxxx111** [water-horse/ICCV2023_SLAM_Challenge#12]
Hello, it is mentioned in the paper (SubT-MRS: A Subterranean, Multi-Robot, Multi-Spectral and Multi-Degraded Dataset for Robust SLAM) that there is a section of calibration dataset about 60 seconds, where can I find it?

**Comment by yuanjun-gao** [comment]
Hi, zhangxiao. Unfortunately, as for SubT-MRS, there is no calibration dataset provided in this challenge
