### ISSUE TITLE
evaluative method

### ISSUE THREAD

**Issue by zzzzxxxx111** [water-horse/ICCV2023_SLAM_Challenge#13]
Hello，I have two questions。first，can you give the code of the evaluation？if not，can you give the formula and units of evaluation。second，Some slam algorithms need to be initialized in motion(vins-mono), in which case, how should the initial position be considered?

**Comment by shibowing** [comment]
Hi Zhangxiao, 

Sorry for late reply because of ICRA deadline. We will post the formula and units soon. 

For question2, we will manually align your estimated trajectory with our ground truth trajectry. 

Feel free to let me know if you still have questions. ^^

**Comment by zzzzxxxx111** [comment]
For the second problem, there is no sensor pose in the initialization part, so there will be a part of the trajectory missing in the initial part, so what to do with this small segment of the trajectory? Will the pose of the missing trajectory be filled in with 0 or with the first estimated pose?

**Comment by zzzzxxxx111** [comment]
May I ask why the last row of the extrinsic parameter matrix of the thermal camera is 0,0,0,0, should not be 0,0,0,1？

**Comment by yuanjun-gao** [comment]
You are right. The last row of the thermal camera's calibration file should be 0, 0, 0, 1

**Comment by shibowing** [comment]
Hi @zhangxiao19980516,  the pose of the missing trajectory be filled in with 0. 

> For the second problem, there is no sensor pose in the initialization part, so there will be a part of the trajectory missing in the initial part, so what to do with this small segment of the trajectory? Will the pose of the missing trajectory be filled in with 0 or with the first estimated pose?

Hi @zhangxiao19980516 , Thanks for reporting issues and will fix it now. For previous question, The missing trajectory will be filled with 0.

**Comment by zzzzxxxx111** [comment]
Thank you very much for your answer. What the means of  four IMU simulation noise parameters provided in question #2 ？
<img width="814" alt="image" src="https://github.com/water-horse/ICCV2023_SLAM_Challenge/assets/63227084/094d3a51-4275-463c-802a-a0ff1d76bdbf">

**Comment by Amigoshan** [comment]
We add bias using a random walk algorithm. The above parameters are used in the random walk model.

**Comment by MukilSaravanan** [comment]
Following up my own question,  https://github.com/water-horse/ICCV2023_SLAM_Challenge/issues/2#issuecomment-1731840943 
Could you please tell where to find IMU parameters (such as gyro, accelero noise density, random walk) used in SubT-MRS and TartanAir?

**Comment by shibowing** [comment]
Hi @MukilSaravanan ,
Sorry for late reply.
The SubT-MRS dataset can provide a reference IMU parameters. However, we cannot provide the calibrated one since the datasets are collected from different time and different robots. For TantarAir, we should have IMU parameters and will upload later. Hi @Amigoshan, could you please post the IMU parameters again?

**Comment by MukilSaravanan** [comment]
> Hi @MukilSaravanan , Sorry for late reply. The SubT-MRS dataset can provide a reference IMU parameters. However, we cannot provide the calibrated one since the datasets are collected from different time and different robots. For TantarAir, we should have IMU parameters and will upload later. Hi @Amigoshan, could you please post the IMU parameters again?

@shibowing, Could you please post it here once? Thanks

**Comment by yuanjun-gao** [comment]
@MukilSaravanan 

> Thank you very much for your answer. What the means of four IMU simulation noise parameters provided in question #2 ？ <img alt="image" width="814" src="https://user-images.githubusercontent.com/63227084/268878119-094d3a51-4275-463c-802a-a0ff1d76bdbf.png">



> We add bias using a random walk algorithm. The above parameters are used in the random walk model.
