### ISSUE TITLE
Could I ask to add my email to your Gradescope course?

### ISSUE THREAD

**Issue by elitechrome** [water-horse/ICCV2023_SLAM_Challenge#14]
Hi, I want to participate in this competition, but I'm not in the school.
I have some problems signing up for Gradescope.
Could you create my account with the following email manually?
ljm6525@gmail.com

**Comment by shibowing** [comment]
Hi! 
Sorry for late reply. I will add your account now.

**Comment by xiangfuli** [comment]
I've added you into the courses.
