### ISSUE TITLE
Sensors intrinsic and extrinsic

### ISSUE THREAD

**Issue by WeilongXia** [water-horse/ICCV2023_SLAM_Challenge#15]
Hi author, Where are the calibration results for these sensors?

**Comment by shibowing** [comment]
Hi WeilongXia,

We provide the calibration results on our websites. Feel free to let us know you cannot find it. For example, If you want to find the calibration for in visual-inertial track. You can find it from our figure. 

https://superodometry.com/iccv23_challenge_VI
![image](https://github.com/water-horse/ICCV2023_SLAM_Challenge/assets/29483569/1063ffd0-f1d4-4177-9af0-ba539501e3b4)

**Comment by WeilongXia** [comment]
Got it, thx a lot~
