### ISSUE TITLE
score

### ISSUE THREAD

**Issue by haoxinnihao** [water-horse/ICCV2023_SLAM_Challenge#18]
Will the results(ATE and RPE) list be announced, and can I know the results of other teams before the game ends?

**Comment by shibowing** [comment]
Hi @haoxinnihao, Thanks for feedback. we are calculating the ATE and RPE now.

**Comment by letsgofeng** [comment]
Hi,  when is Leaderboard open on Gradescope?
In addition, the position for entering the group name was not found by referring to the fourth submission guide "4. ... Also please remember to input the group name as the leaderboard name. "

**Comment by yuanjun-gao** [comment]
Hi feng, the leaderboard will be open on Sept 28. Totally agree that the group name should appear on the leaderboard.

**Comment by haoxinnihao** [comment]
where can I see the leaderboard?

**Comment by shibowing** [comment]
The leader borad has been updated on the websites. 
https://superodometry.com/datasets
