### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by YibinWu** [water-horse/ICCV2023_SLAM_Challenge#19]
Hi there,
**Will the report be open to the public somewhere at some point or it will be kept confidential?** 
**Is it possible to submit it later?** 
Thanks a lot.

**Comment by shibowing** [comment]
Hi Yibin,

Good to hear from you. 

Unfortunately, the report cannot be submitted later since we need to be fair for all the teams.

However, the report can be confidential now. If we want to public somewhere in future, we will contact you first and ask your suggestions. 

Thank you! 

Best,

**Comment by letsgofeng** [comment]
Hi, when is the deadline for the report submission?

**Comment by shibowing** [comment]
Hi @letsgofeng , the report deadline is 09/25/2023.
