### ISSUE TITLE
The IMU data in the TartanAir dataset

### ISSUE THREAD

**Issue by letsgofeng** [water-horse/ICCV2023_SLAM_Challenge#2]
Will there be any problems with the IMU data in the TartanAir dataset? I found that the IMU data is very noisy during testing.
For example, the error of any two consecutive frames/keyframes of IMU angular velocity integration in other datasets (SubT-MRS 
 and EuRoC datasets) is far less than one degree, but the error of any two consecutive frames/keyframes of IMU angular velocity integration in the TartanAir dataset can reach several degrees to more than ten degrees.

**Comment by Amigoshan** [comment]
Hi, we added the noise manually to IMU data, in order to simulate the noise level of a consumer-grade IMU sensor, like the one in realsense camera. 
I think it is expected that this results in an IMU that is more noisy than the SubT dataset. 
If you are interested, here are the parameters we used to generate the noise: 

accel_realsense_official = {
    'b'         : np.array([0.6859999999999999, 0.6859999999999999, 0.6859999999999999]),
    'b_drift'   : np.array([0.000294, 0.000294, 0.000294]),
    'b_corr'    : np.array([100., 100., 100.]),
    'vrw'       : np.array([0.020788939366884498, 0.020788939366884498, 0.020788939366884498]) * 60 / 60 * np.sqrt(1./200),
    # https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmi055-ds000.pdf
}

gyro_realsense_official = {
    'b'         : np.array([0.017453292519943295, 0.017453292519943295, 0.017453292519943295]),
    'b_drift'   : np.array([9.69627362219072e-06, 9.69627362219072e-06, 9.69627362219072e-06,]),
    'b_corr'    : np.array([100., 100., 100.,]),
    'arw'       : np.array([0.003455575618567618, 0.003455575618567618, 0.003455575618567618]) * 60 / 60 * np.sqrt(1./200),
    # https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmi055-ds000.pdf
}

**Comment by letsgofeng** [comment]
Hi, thanks for your detailed reply. But I still suspect that there is some problems with the IMU data.
May I ask if you have tested your TartanAir dataset in open source monocular+IMU SLAM systems?
I tested open source SLAM systems (such as VINS-Mono: https://github.com/HKUST-Aerial-Robotics/VINS-Mono), and all three sequences failed in the monocular+IMU initialization.
I also tested monocular SLAM, all three sequences can run successfully.

In addition, I want to confirm that the timestamp of the camera and IMU is synchronized? Is the extrinsic parameter an identity matrix?

**Comment by Amigoshan** [comment]
Hmm, it might be about the extrinsics. Thanks for bringing this up! 
We tested the sequence before but not with these specific sequences. The IMU is measured in the NED frame. 
Let me double check and I'll put a more detailed explanation on the website.

**Comment by letsgofeng** [comment]
Hi, I would like to ask if there are any further results.

**Comment by shibowing** [comment]
Hi, we have latest results and @water-horse  will update it and make an annoucenment today.

**Comment by yuanjun-gao** [comment]
Sorry for the late update. The laser_to_imu extrinsics of the three TartanAir trajectories in the LiDAR-inertial track is updated to be:
[0.0, 1.0, 0.0, 0.0,
1.0, 0.0, 0.0, 0.0,
0.0, 0.0,-1.0, 0.0,
0.0, 0.0, 0.0, 1.0]

This is also updated in the [website](https://superodometry.com/iccv23_challenge_LiI)

**Comment by yuanjun-gao** [comment]
The rgb_camera_to_imu extrinsics of the three TartanAir trajectories in the visual-inertial track is also updated to be
[0.0, 1.0, 0.0, 0.0,
0.0, 0.0, 1.0, 0.0,
1.0, 0.0, 0.0, 0.0,
0.0, 0.0, 0.0, 1.0]

This is also updated in the [website](https://superodometry.com/iccv23_challenge_VI)

**Comment by 1baiyu1** [comment]
Hello, we would like to know where IMU's internal references were released in the Visual-Inertial SLAM Challenge

**Comment by yuanjun-gao** [comment]
Hi 1baiyu1. I am assuming you ask about the relationship between the initial IMU frame and Earth. In that case, the following answer will be sufficient for this challenge:
A vertical acceleration upward increases the lin_acc_z value only.

If this does not answer your question, please elaborate your thought.

**Comment by 1baiyu1** [comment]
@water-horse I'm sorry I didn't describe the problem clearly. In fact, what I want to know is the IMU's parameters, just like acc_ n，gyr_n.I'm not sure if it was due to my negligence, but I did not find this information，Thankyou

**Comment by yuanjun-gao** [comment]
For the IMU in SubT dataset, [this page](https://github.com/water-horse/ICCV2023_SLAM_Challenge/blob/master/Hardware_Information.md) contains relevant information including how we model the noise. For the noise parameters of the IMU in TartanAir, it's answered above. @1baiyu1

**Comment by MukilSaravanan** [comment]
> @water-horse I'm sorry I didn't describe the problem clearly. In fact, what I want to know is the IMU's parameters, just like acc_ n，gyr_n.I'm not sure if it was due to my negligence, but I did not find this information，Thankyou

Hi, could you find the noise parameters (such as gyro, accelero noise density, random walk) of the IMU used in SubT-MRS and TartanAir? Thanks in advance

**Comment by shibowing** [comment]
Hi @MukilSaravanan , sorry for late reply.  we didn't have noise parameters since the dataset are collected from different payload. However, we can provide the reference one we used in our SLAM system. Will upload on our website recently.

**Comment by liliang2655** [comment]
> 您好，感谢您的详细回复。但我仍然怀疑 IMU 数据存在一些问题。请问您是否在开源单目+IMU SLAM系统中测试过TartanAir数据集？我测试了开源SLAM系统（例如VINS-Mono：https://github.com/HKUST-Aerial-Robotics/VINS-Mono），所有三个序列在单眼+IMU初始化中都失败了。我还测试了单目SLAM，所有三个序列都可以成功运行。
> 
> 另外，我想确认相机和IMU的时间戳是否同步？外在参数是单位矩阵吗？

大佬您好，您最后用vins-mono可以跑SubT-MRS 吗，我跑了一下，飘得离谱。他最后回答你感觉答非所问，还是没说SubT-MRS 的IMU内参是多少。而且我怀疑相机内参和外参也不准。或者IMU时间戳没对齐。

**Comment by Torchmm** [comment]
So, what is the imu noise parameters in subt-mrs datasets?
