### ISSUE TITLE
Coordinate of TartanAir  Dataset

### ISSUE THREAD

**Issue by haoxinnihao** [water-horse/ICCV2023_SLAM_Challenge#25]
The groundtruth of the TA data set is ned coordinate system or the ordinary rectangular coordinate system that Z axis upward?

**Comment by shibowing** [comment]
Hi, sorry for late reply, the answer could be found in this issue https://github.com/water-horse/ICCV2023_SLAM_Challenge/issues/2

**Comment by shibowing** [comment]
Hi all, here is the coordinate of the Tartan Air dataset.  Feel free to let me know if you still have question. 

![image](https://github.com/water-horse/ICCV2023_SLAM_Challenge/assets/29483569/6575eab6-679b-42df-95f1-dfaa01ad7e3f)
