### ISSUE TITLE
certificate

### ISSUE THREAD

**Issue by haoxinnihao** [water-horse/ICCV2023_SLAM_Challenge#26]
After the seminar, will grade proof of competition results be provided?such  as certificate.

**Comment by shibowing** [comment]
Yes, we are making the certificate and it may take 2 weeks to finish it. We will send it through email.

**Comment by zzzzxxxx111** [comment]
Hello, is the name on the certificate the team name? Or the name of the member on the report.

**Comment by shibowing** [comment]
We will show the name of member. ^^

**Comment by samsdolphin** [comment]
> Yes, we are making the certificate and it may take 2 weeks to finish it. We will send it through email.

Hi @shibowing, any updates on this?

**Comment by zzzzxxxx111** [comment]
Hello @shibowing  When will the certificate be issued?

**Comment by shibowing** [comment]
Hi all, sorry for the delay. I just received  the email from the CMU professor. The certificate will be sent on Nov 18th.

**Comment by shibowing** [comment]
Hi all,

Sorry for the delay.  We are nearly there; just one more professor's signature is needed. I received confirmation a few hours ago that this will be completed within the week.

As such, I anticipate that we will be able to send out the certificate by November 18th. On the same day, I'll also provide instructions for you on the winner team prize.

Thank you very much for your patience and understanding during this process.

Best regards,
