### ISSUE TITLE
Leaderboard update?

### ISSUE THREAD

**Issue by samsdolphin** [water-horse/ICCV2023_SLAM_Challenge#27]
Dear Organizers of the ICCV SLAM Challenge,

Thank you for your effort in organizing such a great SLAM competition.

When will the **official website** of this challenge and the **leaderboard** be updated since the team name is currently my GitHub account name?

Thank you!

**Comment by shibowing** [comment]
Hi @samsdolphin, 

Thanks for reminder! We will update the website recently.

**Comment by samsdolphin** [comment]
> Hi @samsdolphin,
> 
> Thanks for reminder! We will update the website recently.

Hi @shibowing, any updates on this?

**Comment by shibowing** [comment]
Hi @samsdolphin , Thanks for asking. We are getting signature from CMU professors on your certificates. There is only one profressor left and I just sent email to him for progress. Once it is done, I will directly send it through email.

**Comment by yuanjun-gao** [comment]
Hi @samsdolphin, the LIO and VIO leaderboard is updated.
