### ISSUE TITLE
Where is the SubT-MRS dataset ?

### ISSUE THREAD

**Issue by diamonazreal** [water-horse/ICCV2023_SLAM_Challenge#29]
Where can I find the SubT-MRS multi-robot dataset？

**Comment by shibowing** [comment]
Hi @diamonazreal, 

The focus of this challenge does not focus on multi-robot systems. Nevertheless, we released small collection of multi-robot data. Specifically, the datasets titled "Final_Challenge_UGV1," "Final_Challenge_UGV2," and "Final_Challenge_UGV3" are multi-robot scenarios. We anticipate releasing additional datasets in the forthcoming months. Please stay updated by visiting our website: [ICCV23 Challenge at SuperOdometry.com](https://superodometry.com/iccv23_challenge_LiI).

![image](https://github.com/yuanjun-gao/ICCV2023_SLAM_Challenge/assets/29483569/e12182cd-5973-461b-8810-bb234b9af05a)

**Comment by LarryDong** [comment]
> Hi @diamonazreal,
> 
> The focus of this challenge does not focus on multi-robot systems. Nevertheless, we released small collection of multi-robot data. Specifically, the datasets titled "Final_Challenge_UGV1," "Final_Challenge_UGV2," and "Final_Challenge_UGV3" are multi-robot scenarios. We anticipate releasing additional datasets in the forthcoming months. Please stay updated by visiting our website: [ICCV23 Challenge at SuperOdometry.com](https://superodometry.com/iccv23_challenge_LiI).
> 
> ![image](https://private-user-images.githubusercontent.com/29483569/302514789-e12182cd-5973-461b-8810-bb234b9af05a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDI3ODIsIm5iZiI6MTcwOTYwMjQ4MiwicGF0aCI6Ii8yOTQ4MzU2OS8zMDI1MTQ3ODktZTEyMTgyY2QtNTk3My00NjFiLTg4MTAtYmIyMzRiOWFmMDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAxMzQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZWM1YjhiZTRhZTMyNTc2ODdlNTM3M2I5ZjBmODM1ODczYzk3NDVlOTRkNjU4NWZmYWI0YTE5N2Q4NjY4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uc1236_BYO2_5CrakvXoeznjq1jQwZm_ubaVI3a-M2o)

Hi,

We're also interested in the platform you're using.  
The sequences provided only tells us the "Robot" is UGV1, 2 or 3, but is there reference that show what are these UGVs?

Also, in ICCV 2023 Challenge, we find platform named "RC7" and "SP1", in following links:
[https://superodometry.com/iccv23_challenge_VI](https://superodometry.com/iccv23_challenge_VI)

We've found the hardware information [here](https://github.com/yuanjun-gao/ICCV2023_SLAM_Challenge/blob/master/Hardware_Information.md): 
![图片](https://github.com/yuanjun-gao/ICCV2023_SLAM_Challenge/assets/14933902/8e977d3b-dd48-41d9-8d25-c032dd6674e6)

I guess "sp1" means spotmini, the 2nd robot. Which one is "RC7"? And are UGV1~3 in this figure?
Hope you could tell us more, thanks.

**Comment by shibowing** [comment]
Hi @LarryDong , 

Thanks for the questions.  The RC7 is 
![image](https://github.com/yuanjun-gao/ICCV2023_SLAM_Challenge/assets/29483569/261091de-b7fd-4e23-891a-0b6dc277c76a)
UGV1~3 are very similar, which can be found here.
![image](https://github.com/yuanjun-gao/ICCV2023_SLAM_Challenge/assets/29483569/1bb1246d-d658-42a2-8198-c9b4da423c2e)

Feel free to let me know if you have more questions.

**Comment by LarryDong** [comment]
@shibowing Thanks for your quick reply.
