### ISSUE TITLE
Request for Access to the SubT-MRS Dataset Download Link

### ISSUE THREAD

**Issue by Gatsby23** [water-horse/ICCV2023_SLAM_Challenge#30]
Dear Processor,

I recently have read your paper "SubT-MRS Dataset: Pushing SLAM Towards All-weather Environments" and I believe it's a wonderful job and could significantly contribute to the research in the SLAM field. However, I have met some difficulty in downloading this dataset since I could not find any download links available.

I would like to inquire if there are plans to make this dataset publicly accessible in the near future, enabling researchers and developers to download and utilize it for further studies and experimentation. If the dataset is already available for public use, could you please provide the download link?

Thank you for your work and contributions. I look forward to your response.

Sincerely,
Qi Wu.

**Comment by shibowing** [comment]
Dear Qi,

Thank you for reaching out with your question and for your interest. The links you're looking for should be accessible via Google Drive. If you encounter any links that are unavailable or inaccessible on your end, could you kindly send me the specific link? I will gladly verify its status and assist you further.

Best regards,

**Comment by jonastbrg** [comment]
Hi!
As Qi mentioned, the work described at the papaer is indeed wonderful and can help a lot to the field of SLAM.

Though, I can't find the google drive link you have mentioned above..
Can you please add the link for the dataset?

Many thanks for your job, and hopefully I would get the chance to use it as well.

Jonathan

**Comment by shibowing** [comment]
Hi  Jonanthan,

Thanks for your interest! Did you check the links form this website?
ICCV 2023 SLAM Challenge - AirLab (superodometry.com)
<https://superodometry.com/datasets>

Best,

**Comment by jonastbrg** [comment]
Thanks for the quick response!

I have indeed checked the links on the website you have mentioned.

Correct me if I'm wrong, but there is a Google Drive link for every challenge (sensor fusion, virtual inertial & LiDAR).

For example, in [Visual-Inertial challenge](https://superodometry.com/iccv23_challenge_VI), there is a [link ](https://drive.google.com/drive/folders/1drrdOTp7L02QhPJtIvpKo6zB21NoNlYb) for 3 different ROS bags.

My question is, whether there is one folder/link which contains all of the datasets mentioned in the paper, which I have missed, or if the dataset is simply split into the 3 challenges.

Jonathan

**Comment by shibowing** [comment]
Hi all, 

We recently cleaned more dataset and released ground truth map. Feel free to check this website 
https://superodometry.com/superloc

Best, 
Shibo
