### ISSUE TITLE
groundtruth

### ISSUE THREAD

**Issue by liliang2655** [water-horse/ICCV2023_SLAM_Challenge#31]
![QQ20240402-103328](https://github.com/yuanjun-gao/ICCV2023_SLAM_Challenge/assets/164995245/a0b057e2-d5b8-4c7e-be85-c5f9ff9ec3a2)
Hello, where can I find the groundtruth files of these data sets? Looking forward to your reply, thank you!

**Comment by shibowing** [comment]
Hi all,
Thanks for try our dataset!

The first ICCV SLAM Challenge has concluded. We have summarized the winning teams’ solutions and provided a detailed analysis of the submitted results. For more insights, please review our [Paper](https://arxiv.org/abs/2307.07607).In response to your requests, we have open-sourced our [Ground Truth ](https://drive.google.com/drive/folders/1el51myR4Zzmxz6Tq2lq660zUVQSH9PoQ?usp=sharing)on our website  to facilitate easier evaluation. 

Looking ahead, we will release more datasets with Ground Truth. Stay tuned for more details! To stay informed with the latest updates, be sure to sign up for our mailing [list](https://docs.google.com/forms/d/e/1FAIpQLSfG3YfsC-_qOIATpRJi5qLHDt27j_XyGg-r6fFCn6QIC9kTvg/viewform?vc=0&c=0&w=1&flr=0)

Let me know if there is something missing! 

Best, 

Shibo

**Comment by liliang2655** [comment]
> Hi all, Thanks for try our dataset!
> 
> The first ICCV SLAM Challenge has concluded. We have summarized the winning teams’ solutions and provided a detailed analysis of the submitted results. For more insights, please review our [Paper](https://arxiv.org/abs/2307.07607).In response to your requests, we have open-sourced our [Ground Truth ](https://drive.google.com/drive/folders/1el51myR4Zzmxz6Tq2lq660zUVQSH9PoQ?usp=sharing)on our website  to facilitate easier evaluation. 
> 
> Looking ahead, we will release more datasets with Ground Truth. Stay tuned for more details! To stay informed with the latest updates, be sure to sign up for our mailing [list](https://docs.google.com/forms/d/e/1FAIpQLSfG3YfsC-_qOIATpRJi5qLHDt27j_XyGg-r6fFCn6QIC9kTvg/viewform?vc=0&c=0&w=1&flr=0)
> 
> Let me know if there is something missing! 
> 
> Best, 
> 
> Shibo

Thank you for your work. I have one more question: In the above dataset, have you calibrated the intrinsic parameters (such as noise and random walk) of the IMU? In SLAM systems like orb3 and VINS, these IMU intrinsic parameters are required; currently, I'm unsure where to locate these parameters.

**Comment by liliang2655** [comment]
> Hi all, Thanks for try our dataset!
> 
> The first ICCV SLAM Challenge has concluded. We have summarized the winning teams’ solutions and provided a detailed analysis of the submitted results. For more insights, please review our [Paper](https://arxiv.org/abs/2307.07607).In response to your requests, we have open-sourced our [Ground Truth ](https://drive.google.com/drive/folders/1el51myR4Zzmxz6Tq2lq660zUVQSH9PoQ?usp=sharing)on our website  to facilitate easier evaluation. 
> 
> Looking ahead, we will release more datasets with Ground Truth. Stay tuned for more details! To stay informed with the latest updates, be sure to sign up for our mailing [list](https://docs.google.com/forms/d/e/1FAIpQLSfG3YfsC-_qOIATpRJi5qLHDt27j_XyGg-r6fFCn6QIC9kTvg/viewform?vc=0&c=0&w=1&flr=0)
> 
> Let me know if there is something missing! 
> 
> Best, 
> 
> Shibo

Could you please tell me where I can find some classic YAML configuration files for SLAM, such as orb3, vinsmono, and so on

**Comment by xuqingyuan2000** [comment]
> > Hi all, Thanks for try our dataset!
> > The first ICCV SLAM Challenge has concluded. We have summarized the winning teams’ solutions and provided a detailed analysis of the submitted results. For more insights, please review our [Paper](https://arxiv.org/abs/2307.07607).In response to your requests, we have open-sourced our [Ground Truth ](https://drive.google.com/drive/folders/1el51myR4Zzmxz6Tq2lq660zUVQSH9PoQ?usp=sharing)on our website  to facilitate easier evaluation.
> > Looking ahead, we will release more datasets with Ground Truth. Stay tuned for more details! To stay informed with the latest updates, be sure to sign up for our mailing [list](https://docs.google.com/forms/d/e/1FAIpQLSfG3YfsC-_qOIATpRJi5qLHDt27j_XyGg-r6fFCn6QIC9kTvg/viewform?vc=0&c=0&w=1&flr=0)
> > Let me know if there is something missing!
> > Best,
> > Shibo
> 
> Could you please tell me where I can find some classic YAML configuration files for SLAM, such as orb3, vinsmono, and so on

I have the same question. Did you solve it?

**Comment by shibowing** [comment]
Hi all, sorry for the late reply. I think probalby you can refer below yaml file to tune VINS-MONO. 

I also upload the reference imu paramter setting files and vins mono yaml file on our website. 

https://superodometry.com/iccv23_challenge_VI

**Comment by shibowing** [comment]
`%YAML:1.0

#common parameters
imu_topic: "/imu/data"
image_topic: "/camera_1/image_raw"

depth_topic: "/velodyne_points"
laser_topic: "/velodyne_points"
odom_topic: "/integrated_to_init"
output_path: "/home/shiboz/visual_odometry/VINS-RGBD"


#set parent frame in the config file
lio_world_frame: "sensor_init"
vins_world_frame: "vins_world"
camera_frame: "vins_camera"
lio_laser_frame: "sensor"
laser_frame: "sensor"
vins_imu_frame: "vins_imu"


use_lidar_odom_meas: 1 # 1   means use lidar odometry constraints in vins system
scale_lidar_absolute_factor: 3

align_camera_lidar_estimation: 1 # align camera and lidar estimation for visualization

# undistorted point cloud parameter
odom_frame_id: "world"
laser_frame_id: "lidar"
undistorted_laser_topic: "/points_correct"
voxelSize: 0.1
blindFront: 0.1
blindBack: -1.0
blindLeft: 0.1
blindRight: -0.1

#pointcloud settings
laser_type: 16
pcl_dist: 10
u_boundary: 10
d_boundary: 10
l_boundary: 40
r_boundary: 40
pcl_min_dist: 0.3
pcl_max_dist: 6
resolution: 0.02

model_type: MEI
camera_name: camera
image_width: 640
image_height: 480
mirror_parameters:
   xi: 1.5967783801524584
distortion_parameters:
   k1: -0.04701957438555236
   k2:  0.28058825271927323
   p1:  0.0004063627333225579
   p2:  -0.00015239154341021015
projection_parameters:
   gamma1: 771.6611713881042
   gamma2: 688.7864250675316
   u0: 317.73333375994946
   v0: 233.53737010585292
lidar_to_cam_tx: 0.0
lidar_to_cam_ty: 0.0
lidar_to_cam_tz: 0.0
lidar_to_cam_rx: 0.0
lidar_to_cam_ry: 0.0
lidar_to_cam_rz: 0.0  
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
  # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
# 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam

extrinsicRotation_imu_camera: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [0.00373945, 0.0024439,  0.99999002,
         -0.99989234, -0.0141801, 0.00377374,
         0.01418918, -0.99989647, 0.00239061]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation_imu_camera: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.17409098,0.04962189,-0.02152957]
#Rotation from laser frame to imu frame, imu^R_laser
extrinsicRotation_imu_laser: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [0.99921290,-0.039519121,-0.003437276,
         0.039516111,0.999218492,-0.000939132,
         0.003471703,0.000802565,0.999993652 ]
#Translation from laser frame to imu frame, imu^T_laser
extrinsicTranslation_imu_laser: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.08,  0.029, 0.03]

#Rotation from laser frame to camera frame, camera^R_laser
extrinsicRotation_camera_laser: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ -0.0552231,   -0.998337,   0.016536, 
          -0.0153134,  -0.0157125,   -0.999759,
          0.998357 ,   -0.055463, -0.0144203]

#Translation from laser frame to camera frame, camera^T_laser
extrinsicTranslation_camera_laser: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.0507002, -0.0166511,-0.172556]
#feature traker paprameters
max_cnt: 200          # max feature number in feature tracking
min_dist: 20            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 1              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
#for handheld, wheeld
acc_n: 0.08          # accelerometer measurement noise standard deviation. #0.2
gyr_n: 0.004         # gyroscope measurement noise standard deviation.     #0.05
acc_w: 0.00004         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-6       # gyroscope bias random work noise standard deviation.     #4.0e-5

#for tracked applications
#acc_n: 0.5          # accelerometer measurement noise standard deviation. #0.2
#gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05
#acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.02
#gyr_w: 2.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5



g_norm: 9.81007       # gravity magnitude

#loop closure parameters
loop_closure: 0                    # start loop closure
fast_relocalization: 0             # useful in real-time and large project
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/shiboz/visual_odometry/VINS-RGBD" # save and load path

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td:  -6.905602612688245e-05         # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
#rolling shutter parameters
rolling_shutter: 0                      # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0.033               # unit: s. rolling shutter read out time per frame (from data sheet).

#visualization parameters
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ`

**Comment by shibowing** [comment]
https://drive.google.com/file/d/1GoiBcekTPUaSDPjhs4kNDNgKYGtMrTSV/view?usp=sharing
