### ISSUE TITLE
GradeScope Submission Link Expired!

### ISSUE THREAD

**Issue by samsdolphin** [water-horse/ICCV2023_SLAM_Challenge#32]
Hi organizers,

Thank you once again for presenting this high-quality SLAM challenge dataset!

I am currently working on a new paper that uses your dataset for evaluation. However, the latest submission date expired on March 15th. Could the submission link on GradeScope be extended for another 3 months? Thanks!

**Comment by shibowing** [comment]
Hi all,
Thanks for try our dataset!

The first ICCV SLAM Challenge has concluded. We have summarized the winning teams’ solutions and provided a detailed analysis of the submitted results. For more insights, please review our [Paper](https://arxiv.org/abs/2307.07607).In response to your requests, we have open-sourced our [Ground Truth ](https://drive.google.com/drive/folders/1el51myR4Zzmxz6Tq2lq660zUVQSH9PoQ?usp=sharing)on our website  to facilitate easier evaluation. 

Looking ahead, we will release more datasets with Ground Truth. Stay tuned for more details! To stay informed with the latest updates, be sure to sign up for our mailing [list](https://docs.google.com/forms/d/e/1FAIpQLSfG3YfsC-_qOIATpRJi5qLHDt27j_XyGg-r6fFCn6QIC9kTvg/viewform?vc=0&c=0&w=1&flr=0)

Let me know if there is something missing! 

Best, 

ICCV SLAM Challenge Committee
