### ISSUE TITLE
Wrong link of subt_ds3 from Sample Datasets of Subt-MRS dataset in the README

### ISSUE THREAD

**Issue by engcang** [water-horse/ICCV2023_SLAM_Challenge#34]
Hi. Thank you for sharing the great quality of datasets.

In the [table of README file](https://github.com/yuanjun-gao/ICCV2023_SLAM_Challenge?tab=readme-ov-file#sample-datasets), I think the subt_ds3 robot's configuration file link is somewhat wrong, it links to the subt_canary.

Please kindly check the link again!

**Comment by shibowing** [comment]
Hi all, 

Thanks for letting me now. Here is the correct link. We also fixed the readme.  
https://drive.google.com/file/d/1Xkm0yNZkELz16PMUgCPqvUzQng9acJKo/view?usp=drive_link
