### ISSUE TITLE
Ground truth map schedule

### ISSUE THREAD

**Issue by JzHuai0108** [water-horse/ICCV2023_SLAM_Challenge#38]
Dear authors,

Thanks for making public the great SubT-MRS dataset. It was mentioned that the ground truth map is on the way.
Can you please specify a date? Or if it is already publicly available, can you please provide a link?

Regards,

**Comment by shibowing** [comment]
Hi all, 
Sorry for the late reply. The ground truth map can be downloaded in the https://superodometry.com/superloc
