### ISSUE TITLE
unable to register the gradescope account

### ISSUE THREAD

**Issue by samsdolphin** [water-horse/ICCV2023_SLAM_Challenge#4]
![微信截图_20230822191959](https://github.com/water-horse/ICCV2023_SLAM_Challenge/assets/12109266/68b8131c-321c-4e42-a368-da744280eae3)
Hi organizers, I cannot register the account at the [Gradescope](https://www.gradescope.com/), which says the invalid course code.

**Comment by xiangfuli** [comment]
Hello samsdolphin, thanks for the feedback. I've tried to used the course Entry Code to enroll in the gradscope and everything went smoothly. Could you try again? 

Or if you can provide your email address, I can manually add you into the course. Thanks.

**Comment by Jerry-jing** [comment]
> 您好，samsdolphin，感谢您的反馈。我尝试使用课程入门代码注册 gradscope，一切都很顺利。你能再试一次吗？
> 
> 或者，如果您可以提供您的电子邮件地址，我可以手动将您添加到课程中。谢谢。
![Screenshot from 2023-08-24 10-03-23](https://github.com/water-horse/ICCV2023_SLAM_Challenge/assets/58756544/fcc7518b-3bdb-4b79-9656-676ca73d8d93)

您好，我也遇到了一样的问题，我的邮箱是izhang_jing@163.com，您可以帮我添加到课程中吗，谢谢您

**Comment by yuanjun-gao** [comment]
> 您好，我也遇到了一样的问题，我的邮箱是[izhang_jing@163.com](mailto:izhang_jing@163.com)，您可以帮我添加到课程中吗，谢谢您

izhang_jing@163.com is added to the visual inertial track

**Comment by wwtinwhu** [comment]
I encounted the same issue. I fixed it by using Carnegie Mellon University as school. @samsdolphin @water-horse @xiangfuli

**Comment by samsdolphin** [comment]
> Hello samsdolphin, thanks for the feedback. I've tried to used the course Entry Code to enroll in the gradscope and everything went smoothly. Could you try again?
> 
> Or if you can provide your email address, I can manually add you into the course. Thanks.

Yes, thanks for your feedback, so this is my email xliuaa@connect.hku.hk.

**Comment by xiangfuli** [comment]
> > Hello samsdolphin, thanks for the feedback. I've tried to used the course Entry Code to enroll in the gradscope and everything went smoothly. Could you try again?
> > Or if you can provide your email address, I can manually add you into the course. Thanks.
> 
> Yes, thanks for your feedback, so this is my email [xliuaa@connect.hku.hk](mailto:xliuaa@connect.hku.hk).

I've added you into the course.

**Comment by xuwuzhou** [comment]
How can I do with issue https://github.com/water-horse/ICCV2023_SLAM_Challenge/issues/6
@xiangfuli

**Comment by xiangfuli** [comment]
> How can I do with issue #6
> @xiangfuli

I've added you into the course.

**Comment by Tee-626** [comment]
I have the same question. And my email is tee.shutong@gmail.com

**Comment by xiangfuli** [comment]
> tee.shutong@gmail.com

Already added you into the courses.
