### ISSUE TITLE
How to simulate snow influences on LiDAR in Airsim

### ISSUE THREAD

**Issue by NsongLiu** [water-horse/ICCV2023_SLAM_Challenge#5]
Hi, thanks for your great dataset. I found that the dataset includes lidar data under the snowy conditions built by Airsim. However, I have found the weather doesn't effect the lidar in UE before. So I'm interested in how to simulate the snowy effects on LiDAR? 
Thank you!

**Comment by Amigoshan** [comment]
Hi, this is more of an Unreal Engine question. We didn't use the snow effect provided by AirSim, nor the LiDAR sensor in the AirSim. We set up the snow in the Unreal Engine in a way that it can be seen in the depth image, by which we generate the LiDAR data.
