### ISSUE TITLE
Can company employees participate in this workshop?

### ISSUE THREAD

**Issue by xuwuzhou** [water-horse/ICCV2023_SLAM_Challenge#6]
It seems that I can no longer register as a student in gradescope
![image](https://github.com/water-horse/ICCV2023_SLAM_Challenge/assets/44218507/8f0ce7c9-b7d0-451b-884d-13040d6e6c46)

If it is possible to allow company employees to participate, can you add my email address:
daniel.zhou@nio.com

**Comment by xiangfuli** [comment]
You are now enrolled in the course.
