### ISSUE TITLE
Is the rosbag of BlockVisual for SubT-MRS Datasets missing?

### ISSUE THREAD

**Issue by Natsu-Akatsuki** [water-horse/ICCV2023_SLAM_Challenge#8]
Sorry, I could not find the **BlockVisual** rosbag for SubT-MRS datasets in the provided link: https://drive.google.com/drive/folders/1bV5oCLrpVoc6xKcIduUcco47nG0jPH6i. Is it missing, or is it my fault?

**Comment by yuanjun-gao** [comment]
Thank you for pointing out. You are right that it is missing and it will soon be uploaded. Sorry about that.
