### ISSUE TITLE
Are there some incorrect description for SubT-MRS Datasets?

### ISSUE THREAD

**Issue by Natsu-Akatsuki** [water-horse/ICCV2023_SLAM_Challenge#9]
Thank you for providing the awesome datasets. I have some questions that I would like to ask about it.

1. Since merging the multiple rosbags into one rosbag of Multi_Floor and Long_Corridor, the durations are 417 and 295, respectively, not the 480 and 332 provided in the table of https://superodometry.com/iccv23_challenge_Mul. Is there something wrong with the description or missing data in the provided rosbags?
2. Since we observe there are no LiDAR data in BlockVisual dataset in folder-format dataset or the rosbag-format dataset , is the sensor description in the table of https://superodometry.com/iccv23_challenge_Mul is wrong or missing data in the provided rosbag?

**Comment by yuanjun-gao** [comment]
Hi @Natsu-Akatsuki the durations of the merged rosbags are the same as the groundtruth trajectory we will use to evaluate submitted trajectories. The durations provided in [https://superodometry.com/iccv23_challenge_Mul](https://superodometry.com/iccv23_challenge_Mul) for Multi_Floor and Long_Corridor are wrong.

The description of BlockVisual in the table of [https://superodometry.com/iccv23_challenge_Mul](https://superodometry.com/iccv23_challenge_Mul) is also wrong. BlockVisual should not contain LiDAR data.

Sorry for the late reply.
